version: "3.9"

services:
  app:
    build: .
    container_name: "space-flight-news_api"
    ports:
     - 3333:3333
    # command: bash -c "npm run test" ##run this to access test database
    command: bash -c "npm run typeorm:development migration:run && npm run dev" ##run this to access development database
    # command: bash -c "npm run typeorm:production migration:run && npm run start" ##run this to access heroku database
    volumes:
      - .:/user/app

  ##run this to access development database
  database:
    image: "postgres"
    container_name: "postgres_space-flight-news_development"
    restart: "always"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=spaceflightnews
      - POSTGRES_PASSWORD=coodesh
      - POSTGRES_DB=space-flight-news
      - PGTZ=UTC
    volumes:
      - pgdata:/data/postgres

  ##run this to access test database
  # database:
  #   image: "postgres"
  #   container_name: "postgres_space-flight-news_tests"
  #   restart: "always"
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=spaceflightnews
  #     - POSTGRES_PASSWORD=coodesh
  #     - POSTGRES_DB=space-flight-news_tests
  #     - PGTZ=UTC
  #   volumes:
  #     - pgdata:/data/postgres

  redis:
    image: "redis:alpine"
    container_name: "redis_space-flight-news_cache"
    restart: "always"
    environment:
      - REDIS_PASSWORD=redispassword
    command: >
        --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
